### ISSUE TITLE
cause: Error: getaddrinfo ENOTFOUND sui.api.scallop.io

### ISSUE THREAD

**Issue by Will-Dong** [scallop-io/sui-scallop-sdk#197]
> Error: AxiosError: getaddrinfo ENOTFOUND sui.api.scallop.io
>     at AxiosError.from (file:///d:/sui-win/sui-overflow-flashloan-strats/node_modules/axios/lib/core/AxiosError.js:89:14)
>     at RedirectableRequest.handleRequestError (file:///d:/sui-win/sui-overflow-flashloan-strats/node_modules/axios/lib/adapters/http.js:610:25)
>     at RedirectableRequest.emit (node:events:531:35)
>     at eventHandlers.<computed> (d:\sui-win\sui-overflow-flashloan-strats\node_modules\follow-redirects\index.js:38:24)
>     at ClientRequest.emit (node:events:519:28)
>     at emitErrorEvent (node:_http_client:108:11)
>     at TLSSocket.socketErrorListener (node:_http_client:511:5)
>     at TLSSocket.emit (node:events:519:28)
>     at emitErrorNT (node:internal/streams/destroy:169:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
>     at Axios.request (file:///d:/sui-win/sui-overflow-flashloan-strats/node_modules/axios/lib/core/Axios.js:45:41)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ScallopAddress.read (file:///d:/sui-win/sui-overflow-flashloan-strats/node_modules/@scallop-io/sui-scallop-sdk/dist/index.mjs:624:24)
>     at async main (file:///d:/sui-win/sui-overflow-flashloan-strats/dist/scallop-sdk-test.js:33:9) {
>   hostname: 'sui.api.scallop.io',
>   syscall: 'getaddrinfo',
>   code: 'ENOTFOUND',
>   errno: -3008,
>   config: {
>     transitional: {
>       silentJSONParsing: true,
>       forcedJSONParsing: true,
>       clarifyTimeoutError: false
>     },
>     adapter: [ 'xhr', 'http', 'fetch' ],
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 30000,
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     env: { FormData: [Function], Blob: [class Blob] },
>     validateStatus: [Function: validateStatus],
>     headers: Object [AxiosHeaders] {
>       Accept: 'application/json',
>       'Content-Type': 'application/json',
>       'User-Agent': 'axios/1.7.2',
>       'Accept-Encoding': 'gzip, compress, deflate, br'
>     },
>     baseURL: 'https://sui.api.scallop.io',
>     method: 'get',
>     url: 'https://sui.api.scallop.io/addresses/6462a088a7ace142bb6d7e9b',
>     data: undefined
>   },
>   request: <ref *1> Writable {
>     _events: {
>       close: undefined,
>       error: [Function: handleRequestError],
>       prefinish: undefined,
>       finish: undefined,
>       drain: undefined,
>       response: [Function: handleResponse],
>       socket: [Array],
>       timeout: undefined,
>       abort: undefined
>     },
>     _writableState: WritableState {
>       highWaterMark: 16384,
>       length: 0,
>       corked: 0,
>       onwrite: [Function: bound onwrite],
>       writelen: 0,
>       bufferedIndex: 0,
>       pendingcb: 0,
>       [Symbol(kState)]: 17580812,
>       [Symbol(kBufferedValue)]: null
>     },
>     _maxListeners: undefined,
>     _options: {
>       maxRedirects: 21,
>       maxBodyLength: Infinity,
>       protocol: 'https:',
>       path: '/addresses/6462a088a7ace142bb6d7e9b',
>       method: 'GET',
>       headers: [Object: null prototype],
>       agents: [Object],
>       auth: undefined,
>       family: undefined,
>       beforeRedirect: [Function: dispatchBeforeRedirect],
>       beforeRedirects: [Object],
>       hostname: 'sui.api.scallop.io',
>       port: '',
>       agent: undefined,
>       nativeProtocols: [Object],
>       pathname: '/addresses/6462a088a7ace142bb6d7e9b'
>     },
>     _ended: true,
>     _ending: true,
>     _redirectCount: 0,
>     _redirects: [],
>     _requestBodyLength: 0,
>     _requestBodyBuffers: [],
>     _eventsCount: 3,
>     _onNativeResponse: [Function (anonymous)],
>     _currentRequest: ClientRequest {
>       _events: [Object: null prototype],
>       _eventsCount: 7,
>       _maxListeners: undefined,
>       outputData: [],
>       outputSize: 0,
>       writable: true,
>       destroyed: false,
>       _last: true,
>       chunkedEncoding: false,
>       shouldKeepAlive: true,
>       maxRequestsOnConnectionReached: false,
>       _defaultKeepAlive: true,
>       useChunkedEncodingByDefault: false,
>       sendDate: false,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       strictContentLength: false,
>       _contentLength: 0,
>       _hasBody: true,
>       _trailer: '',
>       finished: true,
>       _headerSent: true,
>       _closed: false,
>       socket: [TLSSocket],
>       _header: 'GET /addresses/6462a088a7ace142bb6d7e9b HTTP/1.1\r\n' +
>         'Accept: application/json\r\n' +
>         'Content-Type: application/json\r\n' +
>         'User-Agent: axios/1.7.2\r\n' +
>         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>         'Host: sui.api.scallop.io\r\n' +
>         'Connection: keep-alive\r\n' +
>         '\r\n',
>       _keepAliveTimeout: 0,
>       _onPendingData: [Function: nop],
>       agent: [Agent],
>       socketPath: undefined,
>       method: 'GET',
>       maxHeaderSize: undefined,
>       insecureHTTPParser: undefined,
>       joinDuplicateHeaders: undefined,
>       path: '/addresses/6462a088a7ace142bb6d7e9b',
>       _ended: false,
>       res: null,
>       aborted: false,
>       timeoutCb: [Function: emitRequestTimeout],
>       upgradeOrConnect: false,
>       parser: null,
>       maxHeadersCount: null,
>       reusedSocket: false,
>       host: 'sui.api.scallop.io',
>       protocol: 'https:',
>       _redirectable: [Circular *1],
>       [Symbol(shapeMode)]: false,
>       [Symbol(kCapture)]: false,
>       [Symbol(kBytesWritten)]: 0,
>       [Symbol(kNeedDrain)]: false,
>       [Symbol(corked)]: 0,
>       [Symbol(kOutHeaders)]: [Object: null prototype],
>       [Symbol(errored)]: null,
>       [Symbol(kHighWaterMark)]: 16384,
>       [Symbol(kRejectNonStandardBodyWrites)]: false,
>       [Symbol(kUniqueHeaders)]: null
>     },
>     _currentUrl: 'https://sui.api.scallop.io/addresses/6462a088a7ace142bb6d7e9b',
>     _timeout: null,
>     [Symbol(shapeMode)]: true,
>     [Symbol(kCapture)]: false
>   },
>   cause: Error: getaddrinfo ENOTFOUND sui.api.scallop.io
>       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
>     errno: -3008,
>     code: 'ENOTFOUND',
>     syscall: 'getaddrinfo',
>     hostname: 'sui.api.scallop.io'
>   }
> }
> 
> [Done] exited with code=0 in 0.658 seconds

**Comment by nicetomeetyou1** [comment]
@Will-Dong Please update your SDK version to latest version
